Add 'resolv' library as a dependency of posix/dns_resolvers.cpp
-lresolv parameter is a part of linker command line. However we
still have a linking problem:

/usr/bin/ld: osquery/tables/networking/libosquery_tables_networking.a(dns_resolvers.cpp.o): undefined reference to symbol '__res_close@@GLIBC_2.2.5'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/libresolv.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

The linker expects *.so that provides the required symbol appended
*after* the static library that needs it.

To fix the issue we explicitly add 'resolv' as a dependency of
networking library. It forces CMake to add all this dependency after
the *.a.