Add gtest library that contains 'main' function definition
It is needed to create binaries with tests and void following linking
error:

$ /usr/bin/c++  -O2 -g -DNDEBUG  -Wno-sign-compare -Wl,-z,relro,-z,now -Wl,--build-id=sha1 -lresolv -pthread osquery/utils/caches/tests/CMakeFiles/osquery_utils_caches_tests_lrutests-test.dir/lru.cpp.o  -o osquery/utils/caches/tests/osquery_utils_caches_tests_lrutests-test /usr/lib/libgtest.so  -lrt -ldl
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/../../../../lib/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'